Events = {}

Events.PLAYER_LAND_PLATFORM = 1
Events.PLAYER_LEAVE_PLATFORM = 2
Events.EXIT_GAME = 3
Events.PLAYERS_COLLIDE = 4

Events.PLAYER_LAND_PLATFORM_PLAY = 5
Events.PLAYER_LAND_PLATFORM_PRACTICE = 6
Events.PLAYER_LAND_PLATFORM_CONFIGURATION = 7
Events.PLAYER_LAND_PLATFORM_EXIT = 8

Events.PLAYER_LEAVE_PLATFORM_PLAY = 9
Events.PLAYER_LEAVE_PLATFORM_PRACTICE = 10
Events.PLAYER_LEAVE_PLATFORM_CONFIGURATION = 11
Events.PLAYER_LEAVE_PLATFORM_EXIT = 12
