Events = {}

Events.PLAYER_LAND_PLATFORM = 1
Events.PLAYER_LEAVE_PLATFORM = 2
Events.EXIT_GAME = 3
Events.PLAYERS_COLLIDE = 4

Events.PLAYER_LAND_PLATFORM_PLAY_MENU = 5
Events.PLAYER_LAND_PLATFORM_PRACTICE = 6
Events.PLAYER_LAND_PLATFORM_CONFIGURATION = 7
Events.PLAYER_LAND_PLATFORM_EXIT = 8
Events.PLAYER_LAND_PLATFORM_SAVE_CONFIG_AND_MENU = 9
Events.PLAYER_LAND_PLATFORM_MENU = 10
Events.PLAYER_LAND_PLATFORM_BOMB_TAG = 11
Events.PLAYER_LAND_PLATFORM_VIRUS_FALL = 12
Events.PLAYER_LAND_PLATFORM_DEATH_BALL = 13
Events.PLAYER_LAND_PLATFORM_SCORES = 14
Events.PLAYER_LAND_PLATFORM_CREDITS = 15
Events.PLAYER_LAND_PLATFORM_PLAY = 16


Events.PLAYER_LEAVE_PLATFORM_PLAY_MENU = -5
Events.PLAYER_LEAVE_PLATFORM_PRACTICE = -6
Events.PLAYER_LEAVE_PLATFORM_CONFIGURATION = -7
Events.PLAYER_LEAVE_PLATFORM_EXIT = -8
Events.PLAYER_LEAVE_PLATFORM_SAVE_CONFIG_AND_MENU = -9
Events.PLAYER_LEAVE_PLATFORM_MENU = -10
Events.PLAYER_LEAVE_PLATFORM_BOMB_TAG = -11
Events.PLAYER_LEAVE_PLATFORM_VIRUS_FALL = -12
Events.PLAYER_LEAVE_PLATFORM_DEATH_BALL = -13
Events.PLAYER_LEAVE_PLATFORM_SCORES = -14
Events.PLAYER_LEAVE_PLATFORM_CREDITS = -15
Events.PLAYER_LEAVE_PLATFORM_PLAY = -16

-- Eventos del minijuego DEATH_BALL
Events.PLAYER_TOUCHED_DEATH_BALL = 40
Events.DEATH_BALL_COLLISION = 41

-- Eventos del minijuego VIRUS_FALL
Events.PLAYER_TOUCHED_VIRUS = 42
