
function handleKeyboard(dt)
	if love.keyboard.isDown("right") then --press the right arrow key to push the ball to the right
		objects.player1.body:applyForce(400, 0)
	elseif love.keyboard.isDown("left") then --press the left arrow key to push the ball to the left
		objects.player1.body:applyForce(-400, 0)
	elseif love.keyboard.isDown("up") then --press the up arrow key to set the ball in the air
		objects.player1.body:setPosition(650/2, 650/2)
		objects.player1.body:setLinearVelocity(0, 0) --we must set the velocity to zero to prevent a potentially large velocity generated by the change in position
	end


end
